name: Docker Image CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: nelonoel/branch-name@v1.0.1
      - name: Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.GHCR_PAT }}
          containerRegistry: true
          tag: |
            latest
            ${{ env.BRANCH_NAME }}
            ${{ github.sha }}
